
organization{
    baseURL="your.ago.org.arcgis.com"
    namedUsers{
        mainUser{
            username="a.named.user.in.your.org"
            password="some.password"
            referer="a.domain.or.ip"
        }
    }
    apps{
        app1{
            clientId="some.app.id"
            clientSecret="some.app.secret"
            grantType="client_credentials"
        }
        app2{
            clientId="some.app.id"
            clientSecret="some.app.secret"
            grantType="client_credentials"
        }
    }
}